name: Wait for a deployment
description: Waits for a deployment to a stack to complete

inputs:
  appName:
    description: "Name of the application"
    required: true
  envName:
    description: "Name of the environment"
    required: true
  timeoutSeconds:
    description: "Maximum amount of time (in seconds) to wait for the deployment to complete"
    required: false
    default: "300"
  dryRun:
    description: "If true, the context will be loaded and inputs will be validated, but the deployment will not be waited for"
    required: false
    default: "false"

outputs:
  stackName:
    description: "Name of the stack"
  stackShortName:
    description: "Short name of the stack"
  baseURL:
    description: "Base URL of the stack"

runs:
  using: 'node20'
  main: 'dist/index.js'
