name: Create a platform stack
description: Creates a stack for the application in the specified environment

inputs:
  appName:
    description: "Name of the application"
    required: true
  envName:
    description: "Name of the environment"
    required: true
  dryRun:
    description: "If true, the stack will not be created"
    required: false
    default: "false"
  githubToken:
    description: "Github token for authenticating with the Github API"
    required: false
    default: ${{ github.token }}
  waitForDeploymentSeconds:
    description: "Number of seconds to wait for the stack deployment to become synced and healthy before succeeding (anything <= 0 means no wait)"
    required: false
    default: '-1'
  postStackDetails:
    description: "Whether details about the stack should be posted to the PR (if invoked from a PR)"
    required: false
    default: 'true'

outputs:
  stackName:
    description: "Name of the stack that was created"
  baseURL:
    description: "Base URL of the stack"

runs:
  using: 'node20'
  main: 'dist/index.js'
