name: Delete a platform stack
description: Deletes the specified stack for the application in the specified environment

inputs:
  appName:
    description: "Name of the application"
    required: true
  envName:
    description: "Name of the environment"
    required: true
  dryRun:
    description: "If true, the stack will not be deleted"
    required: false
    default: "false"
  githubToken:
    description: "Github token for authenticating with the Github API"
    required: false
    default: ${{ github.token }}

outputs:
  stackName:
    description: "Name of the stack that was deleted"

runs:
  using: 'node20'
  main: 'dist/index.js'
