project_name: argus

builds:
  - skip: true
    binary: argus
    # goos:
    #   - darwin
    #   # - linux
    # goarch:
    #   # - amd64
    #   - arm64

release:
  github:
    owner: chanzuckerberg
    name: argus-artifacts

brews:
  - description: "The command line tool for the Argus platform."
    repository:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/argus-artifacts"
    test: system "#{bin}/argus version"
