on:
  release:
    types: [published]

name: release-cli
jobs:
  go-release-cli:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # For why we need to generate a token and not use the default
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
          private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: chanzuckerberg/core-platform
          path: core-platform

      # - uses: actions/checkout@v4
      #   # we need to fetch all history and tags,
      #   # so we build the proper version
      #   # NOTE: this needs to happen after the tag is created so the tag is present locally
      #   with:
      #     fetch-depth: 0
      #     token: ${{ steps.generate_token.outputs.token }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          workdir: core-platform/core/cli
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
