on:
  push:
    tags:
      - '*'

env:
  SOURCE_REPO: core-platform

name: release
jobs:
  release-artifacts:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # For why we need to generate a token and not use the default
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
          private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}

      # clone the artifact repo
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          path: ${{ github.event.repository.name }}

      # clone the source repo
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: chanzuckerberg/${{ env.SOURCE_REPO }}
          path: ${{ env.SOURCE_REPO }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.SOURCE_REPO }}/core/go.mod
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          workdir: ${{ env.SOURCE_REPO }}/core/cli/
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
